model:
  type: "gradient_boosting"
  params:
    max_depth: 6
    learning_rate: 0.1
    n_estimators: 100
    min_child_weight: 1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42

data:
  train_path: "data/processed/train.csv"
  test_path: "data/processed/test.csv"
  features:
    core_subjects:
      - "ol_mathematics"
      - "ol_science"
      - "ol_english"
    progress_status:
      - "ol_passed"          # Whether passed O/L
      - "al_attempted"       # Whether attempted A/L
      - "al_passed"         # Whether passed A/L
      - "university_entrance"  # Whether qualified for university
      - "university_completed" # Whether completed university
    al_info:
      - "al_stream"
      - "al_physics"
      - "al_chemistry"
      - "al_commerce"
      - "al_zscore"
    university_info:
      - "university_program"
      - "university_gpa"
    additional:
      - "interests"
      - "skills"
  target_columns:
    - "career_path"
    - "education_path"

training:
  test_size: 0.2
  validation_size: 0.2
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
  
preprocessing:
  numerical_features:
    strategy: "standard_scaler"
  categorical_features:
    strategy: "label_encoding"
  text_features:
    strategy: "tfidf"  # For processing interests, skills
