# Model Configuration for Next Step AI

# Stage 1: A/L Stream Predictor
al_stream_predictor:
  model_type: 'xgboost'
  params:
    max_depth: 6
    learning_rate: 0.1
    n_estimators: 100
    min_child_weight: 1
    subsample: 0.8
    colsample_bytree: 0.8
  features:
    - ol_mathematics
    - ol_science
    - ol_english
    - ol_sinhala
    - ol_history
    - ol_religion
    - ol_literature
    - ol_ict
    - ol_commerce
  target: al_stream
  metrics:
    - accuracy
    - precision
    - recall
    - f1

# Stage 2: University Program Predictor
university_predictor:
  model_type: 'lightgbm'
  params:
    num_leaves: 31
    learning_rate: 0.05
    n_estimators: 150
    feature_fraction: 0.9
  features:
    - all_ol_subjects
    - al_stream
    - al_subject_1
    - al_subject_2
    - al_subject_3
    - al_zscore
  target: university_program
  metrics:
    - accuracy
    - precision
    - recall
    - f1

# Stage 3: Career Path Predictor
career_predictor:
  model_type: 'ensemble'
  base_models:
    - model_type: 'xgboost'
      weight: 0.6
      params:
        max_depth: 7
        learning_rate: 0.1
        n_estimators: 120
    - model_type: 'random_forest'
      weight: 0.4
      params:
        n_estimators: 100
        max_depth: 10
  features:
    - all_educational_features
    - university_program
    - university_gpa
  target: career_path
  metrics:
    - accuracy
    - precision
    - recall
    - f1

# Common Parameters
common:
  random_state: 42
  test_size: 0.2
  cv_folds: 5
  early_stopping_rounds: 10
